apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - playwright-tests.yaml
  - elasticsearch.yaml
  - kibana.yaml

commonLabels:
  app: playwright-automation
  environment: base 