apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

namePrefix: qa-

commonLabels:
  environment: qa

patchesStrategicMerge:
  - playwright-tests-patch.yaml

configMapGenerator:
  - name: playwright-config
    literals:
      - BASE_URL=https://qa.example.com
      - WORKERS=2
      - RETRIES=2
      - DEBUG=true
      - SCREENSHOT_ON_FAILURE=true 